# Generated by Django 6.1 on 2026-08-31 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.CharField(max_length=100, unique=True)),
                ('lesson_number', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('date', models.CharField(blank=True, default='', max_length=100)),
                ('time', models.CharField(blank=True, default='14:00 - 16:00', max_length=100)),
                ('status', models.CharField(default='planned', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('homework', models.TextField(blank=True, default='')),
                ('materials', models.JSONField(blank=True, default=list)),
                ('tasks', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['lesson_number'],
            },
        ),
    ]
