# Generated by Django 6.1 on 2026-09-01 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_app', '0002_lesson_code_examples_lesson_goal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('schedule_days', models.CharField(default='Dush / Chor / Juma', max_length=255)),
                ('schedule_time', models.CharField(default='14:00 - 16:00', max_length=100)),
                ('student_count', models.IntegerField(blank=True, default=0, null=True)),
                ('telegram_link', models.URLField(blank=True, default='', max_length=500)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Rejalashtirilgan'), ('current', 'Jarayonda'), ('completed', 'O‘tildi'), ('cancelled', 'Qoldirildi')], default='planned', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='lessons_app.group')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons_app.lesson')),
            ],
            options={
                'ordering': ['lesson__lesson_number'],
                'constraints': [models.UniqueConstraint(fields=('group', 'lesson'), name='unique_group_lesson_progress')],
            },
        ),
    ]
