# Generated by Django 6.1 on 2026-09-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_app', '0004_quiz_quizsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(default='Python Backend', max_length=100)),
                ('question_count', models.IntegerField(default=10)),
                ('difficulty', models.CharField(default='medium', max_length=50)),
                ('lesson_ids', models.JSONField(blank=True, default=list)),
                ('custom_questions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
